<a href="https://colab.research.google.com/github/parth-4895/Machine-Learning/blob/main/FeatureEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/content/kc_house_data.csv')
df

               id             date  ...  sqft_living15  sqft_lot15
0      7129300520  20141013T000000  ...           1340        5650
1      6414100192  20141209T000000  ...           1690        7639
2      5631500400  20150225T000000  ...           2720        8062
3      2487200875  20141209T000000  ...           1360        5000
4      1954400510  20150218T000000  ...           1800        7503
...           ...              ...  ...            ...         ...
21608   263000018  20140521T000000  ...           1530        1509
21609  6600060120  20150223T000000  ...           1830        7200
21610  1523300141  20140623T000000  ...           1020        2007
21611   291310100  20150116T000000  ...           1410        1287
21612  1523300157  20141015T000000  ...           1020        1357

[21613 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [5]:
df["date_parsed_dayfirst"]=pd.to_datetime(df["date"], dayfirst=False, errors= "coerce")

In [6]:
df.head()

           id             date  ...  sqft_lot15  date_parsed_dayfirst
0  7129300520  20141013T000000  ...        5650            2014-10-13
1  6414100192  20141209T000000  ...        7639            2014-12-09
2  5631500400  20150225T000000  ...        8062            2015-02-25
3  2487200875  20141209T000000  ...        5000            2014-12-09
4  1954400510  20150218T000000  ...        7503            2015-02-18

[5 rows x 22 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21613 non-null  int64
 1   date                  21613 non-null  object
 2   price                 21613 non-null  float64
 3   bedrooms              21613 non-null  int64
 4   bathrooms             21613 non-null  float64
 5   sqft_living           21613 non-null  int64
 6   sqft_lot              21613 non-null  int64
 7   floors                21613 non-null  float64
 8   waterfront            21613 non-null  int64
 9   view                  21613 non-null  int64
 10  condition             21613 non-null  int64
 11  grade                 21613 non-null  int64
 12  sqft_above            21613 non-null  int64
 13  sqft_basement         21613 non-null  int64
 14  yr_built              21613 non-null  int64
 15  yr_renovated          21613 non-null  int64
 16  zipcode               21613 non-null  int64
 17  lat                   21613 non-null  float64
 18  long                  21613 non-null  float64
 19  sqft_living15         21613 non-null  int64
 20  sqft_lot15            21613 non-null  int64
 21  date_parsed_dayfirst  21613 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(15), object(1)
memory usage: 3.6+ MB

In [8]:
df["year"]=df["date_parsed_dayfirst"].dt.year.astype("Int32")

In [9]:
df.sample(10)

               id             date  ...  date_parsed_dayfirst  year
17816  1036400100  20141021T000000  ...            2014-10-21  2014
4167   2474400300  20150506T000000  ...            2015-05-06  2015
13113  7137300040  20150504T000000  ...            2015-05-04  2015
5237   6076500364  20140910T000000  ...            2014-09-10  2014
5682   2115720500  20141023T000000  ...            2014-10-23  2014
13867  7524950210  20150401T000000  ...            2015-04-01  2015
3685   3861400061  20150213T000000  ...            2015-02-13  2015
18046  4045700455  20150316T000000  ...            2015-03-16  2015
9465   4123800580  20140812T000000  ...            2014-08-12  2014
9168   5104530770  20150121T000000  ...            2015-01-21  2015

[10 rows x 23 columns]

In [15]:
df["bathrooms"]=df["bathrooms"].astype("Int32", errors="ignore")
df["floors"]=df["floors"].astype("Int32", errors="ignore")

In [16]:
df.sample(10)

               id             date  ...  date_parsed_dayfirst  year
13911  7517500085  20150425T000000  ...            2015-04-25  2015
6897   1099760470  20140604T000000  ...            2014-06-04  2014
6395   8148600020  20140926T000000  ...            2014-09-26  2014
20691  2902200240  20140610T000000  ...            2014-06-10  2014
17869  2122059198  20140825T000000  ...            2014-08-25  2014
16256  7579200715  20141205T000000  ...            2014-12-05  2014
20970   993001563  20140522T000000  ...            2014-05-22  2014
7486   3275800050  20141022T000000  ...            2014-10-22  2014
16103  7418000020  20140724T000000  ...            2014-07-24  2014
8059   2600010330  20150120T000000  ...            2015-01-20  2015

[10 rows x 23 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21613 non-null  int64
 1   date                  21613 non-null  object
 2   price                 21613 non-null  float64
 3   bedrooms              21613 non-null  int64
 4   bathrooms             21613 non-null  float64
 5   sqft_living           21613 non-null  int64
 6   sqft_lot              21613 non-null  int64
 7   floors                21613 non-null  float64
 8   waterfront            21613 non-null  int64
 9   view                  21613 non-null  int64
 10  condition             21613 non-null  int64
 11  grade                 21613 non-null  int64
 12  sqft_above            21613 non-null  int64
 13  sqft_basement         21613 non-null  int64
 14  yr_built              21613 non-null  int64
 15  yr_renovated          21613 non-null  int64
 16  zipcode               21613 non-null  int64
 17  lat                   21613 non-null  float64
 18  long                  21613 non-null  float64
 19  sqft_living15         21613 non-null  int64
 20  sqft_lot15            21613 non-null  int64
 21  date_parsed_dayfirst  21613 non-null  datetime64[ns]
 22  year                  21613 non-null  Int32
dtypes: Int32(1), datetime64[ns](1), float64(5), int64(15), object(1)
memory usage: 3.7+ MB

In [18]:
df['bathrooms'] = np.floor(pd.to_numeric(df['bathrooms'], errors='coerce')).astype('Int32')

In [19]:
df.head(
)

           id             date     price  ...  sqft_lot15  date_parsed_dayfirst  year
0  7129300520  20141013T000000  221900.0  ...        5650            2014-10-13  2014
1  6414100192  20141209T000000  538000.0  ...        7639            2014-12-09  2014
2  5631500400  20150225T000000  180000.0  ...        8062            2015-02-25  2015
3  2487200875  20141209T000000  604000.0  ...        5000            2014-12-09  2014
4  1954400510  20150218T000000  510000.0  ...        7503            2015-02-18  2015

[5 rows x 23 columns]

In [20]:
df['floors'] = np.floor(pd.to_numeric(df['floors'], errors='coerce')).astype('Int32')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21613 non-null  int64
 1   date                  21613 non-null  object
 2   price                 21613 non-null  float64
 3   bedrooms              21613 non-null  int64
 4   bathrooms             21613 non-null  Int32
 5   sqft_living           21613 non-null  int64
 6   sqft_lot              21613 non-null  int64
 7   floors                21613 non-null  Int32
 8   waterfront            21613 non-null  int64
 9   view                  21613 non-null  int64
 10  condition             21613 non-null  int64
 11  grade                 21613 non-null  int64
 12  sqft_above            21613 non-null  int64
 13  sqft_basement         21613 non-null  int64
 14  yr_built              21613 non-null  int64
 15  yr_renovated          21613 non-null  int64
 16  zipcode               21613 non-null  int64
 17  lat                   21613 non-null  float64
 18  long                  21613 non-null  float64
 19  sqft_living15         21613 non-null  int64
 20  sqft_lot15            21613 non-null  int64
 21  date_parsed_dayfirst  21613 non-null  datetime64[ns]
 22  year                  21613 non-null  Int32
dtypes: Int32(3), datetime64[ns](1), float64(3), int64(15), object(1)
memory usage: 3.6+ MB

In [22]:
df["bedrooms"]=df["bedrooms"].astype("Int32")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21613 non-null  int64
 1   date                  21613 non-null  object
 2   price                 21613 non-null  float64
 3   bedrooms              21613 non-null  Int32
 4   bathrooms             21613 non-null  Int32
 5   sqft_living           21613 non-null  int64
 6   sqft_lot              21613 non-null  int64
 7   floors                21613 non-null  Int32
 8   waterfront            21613 non-null  int64
 9   view                  21613 non-null  int64
 10  condition             21613 non-null  int64
 11  grade                 21613 non-null  int64
 12  sqft_above            21613 non-null  int64
 13  sqft_basement         21613 non-null  int64
 14  yr_built              21613 non-null  int64
 15  yr_renovated          21613 non-null  int64
 16  zipcode               21613 non-null  int64
 17  lat                   21613 non-null  float64
 18  long                  21613 non-null  float64
 19  sqft_living15         21613 non-null  int64
 20  sqft_lot15            21613 non-null  int64
 21  date_parsed_dayfirst  21613 non-null  datetime64[ns]
 22  year                  21613 non-null  Int32
dtypes: Int32(4), datetime64[ns](1), float64(3), int64(14), object(1)
memory usage: 3.5+ MB

In [24]:
df["bed&bathR"] = df["bedrooms"]+df["bathrooms"]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21613 non-null  int64
 1   date                  21613 non-null  object
 2   price                 21613 non-null  float64
 3   bedrooms              21613 non-null  Int32
 4   bathrooms             21613 non-null  Int32
 5   sqft_living           21613 non-null  int64
 6   sqft_lot              21613 non-null  int64
 7   floors                21613 non-null  Int32
 8   waterfront            21613 non-null  int64
 9   view                  21613 non-null  int64
 10  condition             21613 non-null  int64
 11  grade                 21613 non-null  int64
 12  sqft_above            21613 non-null  int64
 13  sqft_basement         21613 non-null  int64
 14  yr_built              21613 non-null  int64
 15  yr_renovated          21613 non-null  int64
 16  zipcode               21613 non-null  int64
 17  lat                   21613 non-null  float64
 18  long                  21613 non-null  float64
 19  sqft_living15         21613 non-null  int64
 20  sqft_lot15            21613 non-null  int64
 21  date_parsed_dayfirst  21613 non-null  datetime64[ns]
 22  year                  21613 non-null  Int32
 23  bed&bathR             21613 non-null  Int32
dtypes: Int32(5), datetime64[ns](1), float64(3), int64(14), object(1)
memory usage: 3.6+ MB

In [26]:
df.sample(10)

               id             date  ...  year  bed&bathR
6508   4217402115  20150421T000000  ...  2015         10
9015   7518500301  20150301T000000  ...  2015          4
3136   1023059313  20150205T000000  ...  2015          5
6802   7429000130  20150509T000000  ...  2015          6
2360   1697000370  20150325T000000  ...  2015          4
19041  2141310580  20141125T000000  ...  2014          6
21567  9521100031  20140618T000000  ...  2014          6
12350  8964800860  20150209T000000  ...  2015          6
1190   2624049185  20140909T000000  ...  2014          4
8057   2722059013  20150204T000000  ...  2015          3

[10 rows x 24 columns]

In [27]:
df.set_index("id")

                       date     price  ...  year  bed&bathR
id                                     ...
7129300520  20141013T000000  221900.0  ...  2014          4
6414100192  20141209T000000  538000.0  ...  2014          5
5631500400  20150225T000000  180000.0  ...  2015          3
2487200875  20141209T000000  604000.0  ...  2014          7
1954400510  20150218T000000  510000.0  ...  2015          5
...                     ...       ...  ...   ...        ...
263000018   20140521T000000  360000.0  ...  2014          5
6600060120  20150223T000000  400000.0  ...  2015          6
1523300141  20140623T000000  402101.0  ...  2014          2
291310100   20150116T000000  400000.0  ...  2015          5
1523300157  20141015T000000  325000.0  ...  2014          2

[21613 rows x 23 columns]

In [28]:
df= df.sort_values("id", ascending=True)

In [29]:
df

               id             date  ...  year  bed&bathR
2497      1000102  20150422T000000  ...  2015          9
2496      1000102  20140916T000000  ...  2014          9
6735      1200019  20140508T000000  ...  2014          5
8411      1200021  20140811T000000  ...  2014          4
8809      2800031  20150401T000000  ...  2015          4
...           ...              ...  ...   ...        ...
16737  9842300095  20140725T000000  ...  2014          7
3260   9842300485  20150311T000000  ...  2015          3
7621   9842300540  20140624T000000  ...  2014          4
20979  9895000040  20140703T000000  ...  2014          3
15951  9900000190  20141030T000000  ...  2014          4

[21613 rows x 24 columns]